apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: sample-app
  newName: ghcr.io/nhattran2108/cicd-test
  newTag: 37be0eefaeaf31664f983d3ca04b874f1b4fe90e
