apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - db-secret.yaml
  - db-pvc.yaml
  - db-deployment.yaml
  - db-service.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
images:
  - name: todolist-db
    newName: ghcr.io/nhattran2108/cicd-test-db
    newTag: latest
  - name: todolist-backend
    newName: ghcr.io/nhattran2108/cicd-test-backend
    newTag: latest
  - name: todolist-frontend
    newName: ghcr.io/nhattran2108/cicd-test-frontend
    newTag: latest
